version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq

  db:
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: hse
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    hostname: localhost
    ports:
      - "5432:5432"
    depends_on:
      - rabbitmq

  web:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      AMQP_HOST: host.docker.internal
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python3 main.py'
    ports:
      - "8000:8000"

networks:
  rabbitmq:
    driver: bridge